In [1]:
import pandas as pd

import seaborn as sb
%matplotlib inline

## Prepare the Data

In [2]:
df = pd.read_csv('../datasets/beer.tsv', sep='\t') 
df['WR'] = df.WR.fillna(0)
df['ABV'] = df.ABV.fillna(0)
df['Type'] = df.Type.fillna("na")

In [3]:
df.Brewery.unique()

array(['The Alchemist', 'Russian River Brewing Company',
       'Founders Brewing Company', 'Three Floyds Brewing Co. & Brewpub',
       'Brouwerij Westvleteren (Sint-Sixtusabdij van Westvleteren)',
       'Goose Island Beer Co.', 'Firestone Walker Brewing Co.',
       'Deschute Brewery', "Bell's Brewing Company", 'Brasserie Cantillon',
       'Brasserie de Rochefort', 'Kern River Brewing Company',
       'Cigar City Brewing', 'Dark Horse Brewing Company',
       'Kuhnhenn Brewing Company', 'Surly Bewing Company',
       'Hill Farmstead Brewery', "Lawson's Finest Liquids", 'The Bruery',
       'Brouwerij St. Bernardus NV', 'The Lost Abbey',
       'Ballast Point Brewing Company',
       'Bayerishe Staatsbrauerei Weihenstephan', 'Smith Brewing Company',
       'Pelican Pub & Brewery', 'Brewery and Tasting Room',
       'Stone Brewing Co.', 'TrÌ¦egs Brewing Company',
       'Brasserie Dieu Du Ciel', 'Boston Beer Company (Samuel Adams)',
       'Lagunitas Brewing Company', 'Alpine Beer Company',
       'FiftyFifty Brewing Company', 'Oskar Blues Brewing Company',
       'Privatbrauerei Franz Inselkammer KG', 'Evil Twin Brewing',
       'Ithaca Beer Company', 'Green Flash Brewing Co.',
       'Raccoon Lodge & Brewpub', 'Brouwerik Drie Fonteinen',
       'De Struise Brouwers', 'Brasserie FantÌ«me',
       'Fat Heads Brewery & Saloon', 'Unibroue',
       'New Glarus Brewing Company', 'Brouwerij Drie Fonteinen',
       'Great Lakes Brewing Company', 'Farmstead Brewery',
       'Hair of the Dog Brewing Company', "Peg's Cantina & Brewpub",
       'Weisses BrÌ_uhaus G. Schneider & Sohn GmbH', 'Maine Beer Company',
       'Minneapolis Town Hall Brewery', 'BiÌ¬res de Chimay S.A.',
       'North Coast Brewing Co.', 'Brouwerij Duvel Moortgat NV',
       'Brouwerij Westmalle', 'Boulevard Brewing Co.',
       'Port Brewing Company', 'Odell Brewing Company',
       'Live Oak Brewing Company', 'Midnight Sun Brewing Co.',
       'Old Hickory Brewery', 'Dogfish Head Brewery', 'Mikkeller ApS',
       'Brouwerij Bockeror N.V.', "Jack's Abby Brewing",
       'Terrapin Beer Company', 'Gueuzerie Tilquin',
       'Foothills Brewing Company', 'The Funky Buddha Lounge & Brewery',
       'NÌ_rke Kulturbryggeri AB', 'Southern Tier Brewing Company',
       'Brouwerij Het Anker', "Hoppin' Frog Brewery",
       'New England Brewing Co.', 'Captain Lawrence Brewing Co.',
       'Perennial Artisan Ales', 'Bear Republic Brewing Co.',
       'Great Divide Brewing Company', 'Brouwerij Rodenbach N.V.',
       'Allagash Brewing Company', 'Central Waters Brewing Company',
       'Kettle Taproom & Smokehouse', "Bootlegger's Brewery",
       'Klosterbrauerei Andechs', 'Brouwerij Bosteels',
       'New Belgium Brewing', 'J.W. Lees & Co. (Brewers) Ltd',
       'Brouwerij Girardin', 'Anchorage Brewing Company',
       'Columbus Brewing Company', 'Samuel Smith Old Brewery',
       'New Belgium Brewing Company', 'Logsdon Farmhouse Ales',
       'Boneyard Beer Company', 'Avery Brewing Company',
       'Epic Brewing Co.', 'Olde Hickory Brewery', 'Dry Dock Brewing Co.',
       'Brouwerij Van Steetnberge N.V.', 'Smuttynose Brewing Company',
       'Big Sky Brewing Company', 'Fremont Brewing Company',
       "Brasserie d'Orval S.A.", 'Central City Brewing'], dtype=object)

In [4]:
df.head()

,Rank,Name,Brewery,Type,ABV,WR,Reviews
0,1,Heady Topper,The Alchemist,Imperial IPA,8.0,4.69,3146
1,2,Pliny The Younger,Russian River Brewing Company,Imperial IPA,11.0,4.65,1572
2,3,Pliny The Elder,Russian River Brewing Company,Imperial IPA,8.0,4.64,6129
3,4,Founders CBS Imperial Stout,Founders Brewing Company,Imperial Stout,10.6,4.63,2026
4,5,Founders KBS (Kentucky Breakfast Stout),Founders Brewing Company,Imperial Stout,11.2,4.61,4714

## Fit and score the model

In [56]:
from sklearn.linear_model import LogisticRegression
from sklearn.cross_validation import train_test_split
model = LogisticRegression()

X = df[['ABV', 'WR']]
y = df['Type']
X_train, X_test, y_train, y_test = train_test_split(X, y)

model.fit(X_train,y_train)
scores = model.score(X_test,y_test)

print(scores)

0.253968253968

## Predict a single entry

In [50]:
l = df.iloc[1][['ABV', 'WR']]
print (l)
print ("Predicted Type: ", model.predict(l))

ABV      11
WR     4.65
Name: 1, dtype: object
Predicted Type:  ['Imperial Stout']

In [57]:
## As we see the real value of this enrty is Imperial IPA. How can we improve the model? 
df.iloc[1]

Rank                                   2
Name                   Pliny The Younger
Brewery    Russian River Brewing Company
Type                        Imperial IPA
ABV                                   11
WR                                  4.65
Reviews                             1572
Name: 1, dtype: object

## Using groupby

In [42]:
df[df['Brewery'] == 'Alpine Beer Company']

,Rank,Name,Brewery,Type,ABV,WR,Reviews
58,59,Nelson,Alpine Beer Company,American IPA,7.10,4.37,1054
59,60,Exponential Hoppiness,Alpine Beer Company,Imperial IPA,11.00,4.37,708
66,67,Hoppy Birthday,Alpine Beer Company,American Pale Ale,5.25,4.36,262
70,71,Duet IPA,Alpine Beer Company,American IPA,7.00,4.35,842
79,80,Pure Hoppiness,Alpine Beer Company,Imperial IPA,8.00,4.34,1116
105,106,Bad Boy,Alpine Beer Company,Imperial IPA,9.00,4.31,253
197,198,Great,Alpine Beer Company,American Barleywine,14.00,4.23,205

In [41]:
df.groupby(["Brewery", "Type"])[['Type']].count()

                                                                    Type
Brewery                                    Type
Allagash Brewing Company                   Belgian Strong Dark Ale     1
                                           Tripel                      1
Alpine Beer Company                        American Barleywine         1
                                           American IPA                2
                                           American Pale Ale           1
                                           Imperial IPA                3
Anchorage Brewing Company                  Belgian IPA                 1
Avery Brewing Company                      Imperial IPA                1
Ballast Point Brewing Company              American IPA                1
                                           Porter                      1
Bayerishe Staatsbrauerei Weihenstephan     Dunkelweizen                1
                                           Weizenbock                  1
                                           na                          1
Bear Republic Brewing Co.                  American IPA                2
                                           Imperial IPA                1
Bell's Brewing Company                     American IPA                1
                                           American Strong Ale         1
                                           Imperial IPA                2
                                           Imperial Stout              2
Big Sky Brewing Company                    Russian Imperial Stout      1
BiÌ¬res de Chimay S.A.                     Belgian Strong Dark Ale     1
Boneyard Beer Company                      Imperial IPA                1
Bootlegger's Brewery                       na                          1
Boston Beer Company (Samuel Adams)         American Strong Ale         1
Boulevard Brewing Co.                      Farmhouse Ale               1
Brasserie Cantillon                        Fruit                       7
                                           Gueuze                      2
                                           Lambic                      1
                                           Lambic Gueuze               1
Brasserie Dieu Du Ciel                     Imperial Stout              1
...                                                                  ...
Stone Brewing Co.                          American Strong Ale         2
                                           Imperial IPA                2
                                           Imperial Stout              2
                                           Russian Imperial Stout      1
Surly Bewing Company                       American IPA                2
                                           Imperial IPA                1
                                           Imperial Stout              1
Terrapin Beer Company                      American Double             1
The Alchemist                              Imperial IPA                1
The Bruery                                 American Strong Ale         1
                                           Flanders Red Ale            1
                                           Imperial Pilsner            1
                                           Imperial Stout              2
                                           Old Ale                     1
The Funky Buddha Lounge & Brewery          American Porter             1
The Lost Abbey                             American Strong Ale         2
                                           Flanders Red Ale            1
                                           Wild Ale                    1
                                           na                          1
Three Floyds Brewing Co. & Brewpub         American Barleywine         1
                                           American IPA                1
                                           American Pale Ale           2
                                           American Pale Wheat Ale     1
                                           Imperial IPA                5
                                           Imperial Stout              2
                                           Russian Imperial Stout      1
TrÌ¦egs Brewing Company                    Red Ale                     1
Unibroue                                   Belgian Strong Dark Ale     1
                                           na                          1
Weisses BrÌ_uhaus G. Schneider & Sohn GmbH Weizenbock                  1

[188 rows x 1 columns]

In [ ]:
df['type_Stout'] = df['Type'].map(lambda k: 1 if 'Stout' in k else 0)
df['type_IPA'] = df['Type'].map(lambda k: 1 if 'IPA' in k else 0)
df['type_Ale'] = df['Type'].map(lambda k: 1 if 'Ale' in k else 0)